default_install_hook_types: [pre-commit]
ci:
  autofix_commit_msg: "[pre-commit]: auto fixes"
  autofix_prs: true
repos:
  - repo: https://github.com/fllesser/ruff-rev-sync-pre-commit
    rev: v1.0.0
    hooks:
      - id: ruff-rev-sync

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.13
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.0
    hooks:
      - id: uv-lock
      - id: uv-sync
